// Episode 23, Story 23.3 — the "Query Health" card. Purely presentational:
// takes an already-computed `QueryHealth` (`computeQueryHealth`,
// src/rules/queryHealth.ts — recomputed by the caller per active statement,
// this component never runs the scoring math itself). Additive to
// PlanReaderPage.tsx's existing plan-shell summary sentence (Story 5.2) —
// the qualitative sentence and this quantitative score are two different,
// complementary views of the same underlying findings; this story does not
// touch summarize.ts or its own callers/tests.

import { useState } from "react"
import { QUERY_HEALTH_DIMENSIONS, type QueryHealth, type QueryHealthDimension } from "../../rules/queryHealth"
import "./queryHealthCard.css"

export interface QueryHealthCardProps {
  health: QueryHealth
}

const DIMENSION_LABEL: Record<QueryHealthDimension, string> = {
  runtime: "Runtime",
  cardinality: "Cardinality",
  memory: "Memory",
  io: "I/O",
  parallelism: "Parallelism",
}

// Matches this app's existing severity color language (OPENERS/summarize.ts,
// the finding-severity tiers) rather than inventing a fourth vocabulary —
// "healthy" here is this card's own name for what those surfaces call "info"/
// clean, chosen because a raw score has no `info`-tier concept of its own.
function scoreTier(score: number): "critical" | "warning" | "healthy" {
  if (score < 50) return "critical"
  if (score < 80) return "warning"
  return "healthy"
}

// The exact mechanism, in plain terms — this is the "not LLM-generated, and
// here's what it actually does" disclosure Episode 23's whole design turns
// on (docs/08-episodes-and-stories.md), not an afterthought. Keep this
// text's claims (30/12-point penalties, worst-instance-per-family, plain
// average of scored dimensions) in sync with queryHealth.ts's own constants
// — a docs-vs-code drift test in this component's own test file checks it.
const METHODOLOGY_TEXT =
  "Deterministic and rule-based — never generated by an AI model. Each of the 5 dimensions below starts at 100 " +
  "and loses 30 points for the worst critical-severity issue of its kind, or 12 for the worst warning-severity " +
  "one (one penalty per kind of issue, not one per occurrence). The overall score is the plain average of " +
  "whichever dimensions had enough data in this plan to score at all — a dimension with no data says so, rather " +
  "than guessing."

export function QueryHealthCard({ health }: QueryHealthCardProps) {
  const [isExpanded, setIsExpanded] = useState(false)
  const [isMethodologyOpen, setIsMethodologyOpen] = useState(false)

  return (
    <section className="query-health-card" data-testid="query-health-card">
      <div className="query-health-card__header">
        <h2 className="query-health-card__title">Query Health</h2>
        <button
          type="button"
          className="query-health-card__methodology-toggle"
          aria-expanded={isMethodologyOpen}
          aria-label="How this score is calculated"
          data-testid="query-health-methodology-toggle"
          onClick={() => setIsMethodologyOpen((v) => !v)}
        >
          ⓘ
        </button>
      </div>

      {isMethodologyOpen && (
        <p className="query-health-card__methodology" data-testid="query-health-methodology">
          {METHODOLOGY_TEXT}
        </p>
      )}

      {health.overall.status === "insufficient-data" ? (
        <p className="query-health-card__insufficient" data-testid="query-health-insufficient">
          Not enough data to score this plan.
        </p>
      ) : (
        <>
          <p
            className={`query-health-card__score query-health-card__score--${scoreTier(health.overall.score)}`}
            data-testid="query-health-score"
          >
            {health.overall.score}
            <span className="query-health-card__score-max"> / 100</span>
          </p>
          <p className="query-health-card__legend" data-testid="query-health-legend">
            <span className="query-health-card__legend-item query-health-card__legend-item--critical">🔴 {health.critical} critical</span>
            <span className="query-health-card__legend-item query-health-card__legend-item--warning">
              🟠 {health.warning} warning{health.warning === 1 ? "" : "s"}
            </span>
            <span className="query-health-card__legend-item query-health-card__legend-item--healthy">🟢 {health.healthy} healthy</span>
          </p>
        </>
      )}

      <button
        type="button"
        className="query-health-card__breakdown-toggle"
        aria-expanded={isExpanded}
        data-testid="query-health-breakdown-toggle"
        onClick={() => setIsExpanded((v) => !v)}
      >
        {isExpanded ? "Hide breakdown" : "Show breakdown"}
      </button>

      {/* Breakdown content is derived straight from the `health` prop on
          every render, never held in local state separately from it — a
          user with this expanded who then switches to a different (or
          insufficient-data) statement never sees a stale frame of the
          PREVIOUS statement's numbers (this story's own edge-case table).

          Story 6.3 — scored dimensions still get one row each (unchanged);
          insufficient-data ones are combined into a SINGLE row ("N metrics
          unavailable for this plan") rather than each consuming its own
          permanently-visible "not enough data" row — the exact clutter
          this story removes. Omitted entirely when every dimension
          scored, never a hollow "0 metrics unavailable" line. */}
      {isExpanded &&
        (() => {
          const scored = QUERY_HEALTH_DIMENSIONS.filter((d) => health.dimensions[d].status === "scored")
          const insufficient = QUERY_HEALTH_DIMENSIONS.filter((d) => health.dimensions[d].status !== "scored")
          return (
            <ul className="query-health-card__breakdown" data-testid="query-health-breakdown">
              {scored.map((dimension) => {
                const result = health.dimensions[dimension]
                if (result.status !== "scored") return null // narrows for TS; `scored` already guarantees this
                return (
                  <li key={dimension} className="query-health-card__dimension" data-testid="query-health-dimension">
                    <span className="query-health-card__dimension-label">{DIMENSION_LABEL[dimension]}</span>
                    <span
                      className={`query-health-card__dimension-score query-health-card__dimension-score--${scoreTier(result.score)}`}
                      data-testid="query-health-dimension-score"
                    >
                      {result.score}
                    </span>
                  </li>
                )
              })}
              {insufficient.length > 0 && (
                // Visibly distinct from a real low score — never the same
                // muted number styling a genuine 20/100 would get, since
                // the two mean opposite things (a real problem vs. an
                // honest absence of signal). See this component's own CSS
                // for the actual visual treatment.
                <li className="query-health-card__dimension query-health-card__dimension--unavailable" data-testid="query-health-dimension-unavailable">
                  <span className="query-health-card__dimension-insufficient" data-testid="query-health-dimension-insufficient">
                    {insufficient.length} metric{insufficient.length === 1 ? "" : "s"} unavailable for this plan
                    <span className="query-health-card__dimension-unavailable-names">
                      {" "}
                      ({insufficient.map((d) => DIMENSION_LABEL[d]).join(", ")})
                    </span>
                  </span>
                </li>
              )}
            </ul>
          )
        })()}
    </section>
  )
}
