import { describe, expect, it } from "vitest"
import { render, screen, fireEvent, within } from "@testing-library/react"
import { QueryHealthCard } from "../QueryHealthCard"
import { CRITICAL_PENALTY, WARNING_PENALTY, type QueryHealth } from "../../../rules/queryHealth"

function health(overrides: Partial<QueryHealth> = {}): QueryHealth {
  return {
    overall: { status: "scored", score: 67 },
    dimensions: {
      runtime: { status: "scored", score: 74 },
      cardinality: { status: "scored", score: 55 },
      memory: { status: "scored", score: 90 },
      io: { status: "insufficient-data" },
      parallelism: { status: "insufficient-data" },
    },
    critical: 2,
    warning: 3,
    healthy: 7,
    ...overrides,
  }
}

describe("QueryHealthCard", () => {
  it("renders the exact overall score and node-scoped severity counts from a known QueryHealth", () => {
    render(<QueryHealthCard health={health()} />)
    expect(screen.getByTestId("query-health-score")).toHaveTextContent("67")
    const legend = screen.getByTestId("query-health-legend")
    expect(within(legend).getByText(/2 critical/)).toBeInTheDocument()
    expect(within(legend).getByText(/3 warnings/)).toBeInTheDocument()
    expect(within(legend).getByText(/7 healthy/)).toBeInTheDocument()
  })

  it("shows an explicit 'not enough data' state at the top level — never a placeholder number", () => {
    render(<QueryHealthCard health={health({ overall: { status: "insufficient-data" } })} />)
    expect(screen.getByTestId("query-health-insufficient")).toHaveTextContent(/not enough data/i)
    expect(screen.queryByTestId("query-health-score")).not.toBeInTheDocument()
  })

  it("the breakdown is collapsed by default and reveals 3 scored rows + 1 combined unavailable row on toggle", () => {
    render(<QueryHealthCard health={health()} />)
    expect(screen.queryByTestId("query-health-breakdown")).not.toBeInTheDocument()

    const toggle = screen.getByTestId("query-health-breakdown-toggle")
    expect(toggle).toHaveAttribute("aria-expanded", "false")
    fireEvent.click(toggle)

    expect(toggle).toHaveAttribute("aria-expanded", "true")
    // Story 6.3 — 3 scored dimensions each get their own row (its own
    // testid); the 2 insufficient-data ones (I/O, Parallelism) combine
    // into ONE separately-testid'd row, not two separate scored-style rows.
    const items = screen.getAllByTestId("query-health-dimension")
    expect(items).toHaveLength(3)
    expect(screen.getByTestId("query-health-dimension-unavailable")).toBeInTheDocument()
  })

  it("an insufficient-data dimension is visibly distinct from a real low score — different testid, not just different text", () => {
    render(<QueryHealthCard health={health()} />)
    fireEvent.click(screen.getByTestId("query-health-breakdown-toggle"))

    // A real, low-ish score (Cardinality: 55) renders as a colored number.
    const scored = screen.getAllByTestId("query-health-dimension-score")
    expect(scored.map((el) => el.textContent)).toEqual(expect.arrayContaining(["55"]))

    // Story 6.3 — insufficient-data dimensions (I/O, Parallelism) render
    // via a COMPLETELY different testid/element, not the same score
    // element with different text — a future refactor can't accidentally
    // collapse the two into looking identical. Combined into ONE row now,
    // not one per dimension, naming both in its own text.
    const insufficient = screen.getAllByTestId("query-health-dimension-insufficient")
    expect(insufficient).toHaveLength(1)
    expect(insufficient[0]).toHaveTextContent("2 metrics unavailable for this plan")
    expect(insufficient[0]).toHaveTextContent("I/O")
    expect(insufficient[0]).toHaveTextContent("Parallelism")
    expect(scored).toHaveLength(3)
  })

  it("the 'how this is calculated' disclosure is reachable and matches the ACTUAL penalty constants — a docs-vs-code drift guard", () => {
    render(<QueryHealthCard health={health()} />)
    expect(screen.queryByTestId("query-health-methodology")).not.toBeInTheDocument()

    fireEvent.click(screen.getByTestId("query-health-methodology-toggle"))
    const methodology = screen.getByTestId("query-health-methodology")
    expect(methodology).toHaveTextContent(new RegExp(`${CRITICAL_PENALTY} points`))
    expect(methodology).toHaveTextContent(new RegExp(`${WARNING_PENALTY} for`))
    expect(methodology.textContent).toMatch(/deterministic/i)
    expect(methodology.textContent).toMatch(/never generated by an AI/i)
  })

  it("re-rendering with a DIFFERENT health prop (simulating a statement switch) shows the new numbers, never stale ones", () => {
    const { rerender } = render(<QueryHealthCard health={health()} />)
    expect(screen.getByTestId("query-health-score")).toHaveTextContent("67")

    rerender(<QueryHealthCard health={health({ overall: { status: "scored", score: 12 }, critical: 5, warning: 0, healthy: 1 })} />)
    expect(screen.getByTestId("query-health-score")).toHaveTextContent("12")
    expect(within(screen.getByTestId("query-health-legend")).getByText(/5 critical/)).toBeInTheDocument()
  })

  it("stays expanded-content-correct after a health-prop change while the breakdown was already open", () => {
    const { rerender } = render(<QueryHealthCard health={health()} />)
    fireEvent.click(screen.getByTestId("query-health-breakdown-toggle"))
    expect(screen.getAllByTestId("query-health-dimension")).toHaveLength(3) // + 1 separately-testid'd combined unavailable row
    expect(screen.getByTestId("query-health-dimension-unavailable")).toBeInTheDocument()

    // New health where every dimension is insufficient-data — the
    // breakdown must reflect THIS prop, not the previous statement's.
    const allInsufficient: QueryHealth = {
      overall: { status: "insufficient-data" },
      dimensions: {
        runtime: { status: "insufficient-data" },
        cardinality: { status: "insufficient-data" },
        memory: { status: "insufficient-data" },
        io: { status: "insufficient-data" },
        parallelism: { status: "insufficient-data" },
      },
      critical: 0,
      warning: 0,
      healthy: 0,
    }
    rerender(<QueryHealthCard health={allInsufficient} />)
    expect(screen.getByTestId("query-health-insufficient")).toBeInTheDocument()
    // All 5 dimensions insufficient — no scored rows at all, still just
    // ONE combined row, not 5.
    expect(screen.queryAllByTestId("query-health-dimension")).toHaveLength(0)
    expect(screen.getAllByTestId("query-health-dimension-insufficient")).toHaveLength(1)
    expect(screen.getByTestId("query-health-dimension-insufficient")).toHaveTextContent("5 metrics unavailable for this plan")
    expect(screen.queryByTestId("query-health-dimension-score")).not.toBeInTheDocument()
  })

  // Story 6.3 — a plan with ZERO insufficient dimensions (every dimension
  // scored) must never show a hollow "0 metrics unavailable" line.
  it("omits the unavailable-metrics row entirely when every dimension scored", () => {
    const allScored: QueryHealth = {
      overall: { status: "scored", score: 90 },
      dimensions: {
        runtime: { status: "scored", score: 90 },
        cardinality: { status: "scored", score: 90 },
        memory: { status: "scored", score: 90 },
        io: { status: "scored", score: 90 },
        parallelism: { status: "scored", score: 90 },
      },
      critical: 0,
      warning: 0,
      healthy: 10,
    }
    render(<QueryHealthCard health={allScored} />)
    fireEvent.click(screen.getByTestId("query-health-breakdown-toggle"))
    expect(screen.getAllByTestId("query-health-dimension")).toHaveLength(5)
    expect(screen.queryByTestId("query-health-dimension-insufficient")).not.toBeInTheDocument()
    expect(screen.queryByTestId("query-health-dimension-unavailable")).not.toBeInTheDocument()
  })

  // Story 23.3's own testing-approach bullet — the graph-visualization
  // skill's standing "mobile-width test for every layout-affecting story"
  // requirement. This component has no width-dependent JS/state (unlike
  // DetailPanel's narrow-viewport variant swap) — its narrow-viewport
  // behavior is entirely CSS flex-wrap, which jsdom doesn't lay out. This
  // test is the honest ceiling of what a component test can verify: the
  // card renders correctly inside an artificially narrow container without
  // throwing or omitting content, not a real pixel-overflow assertion.
  it("renders correctly inside a narrow container (structural mobile-width check — real layout verified in a browser)", () => {
    const { container } = render(
      <div style={{ width: 280 }}>
        <QueryHealthCard health={health()} />
      </div>,
    )
    expect(within(container).getByTestId("query-health-card")).toBeInTheDocument()
    fireEvent.click(screen.getByTestId("query-health-breakdown-toggle"))
    expect(screen.getAllByTestId("query-health-dimension")).toHaveLength(3)
    expect(screen.getByTestId("query-health-dimension-unavailable")).toBeInTheDocument()
  })
})
